import { useState, useCallback } from 'react'
import type { ReviewState, Section, IssueSeverity } from '../types'
import { Card, CardHeader, CardTitle, CardContent } from './ui/Card'
import { Button } from './ui/Button'

interface ReportGeneratorProps {
  state: ReviewState
  calculateScore: (section: Section) => number
}

function generateMarkdownReport(
  state: ReviewState,
  calculateScore: (section: Section) => number
): string {
  const lines: string[] = []
  const timestamp = new Date().toISOString().split('T')[0]

  lines.push(`# Paper Review Report`)
  lines.push(``)
  lines.push(`**Paper:** ${state.paperTitle || 'Untitled'}`)
  lines.push(`**Date:** ${timestamp}`)
  lines.push(`**Overall Score:** ${state.overallScore.toFixed(1)} / 10`)
  lines.push(``)

  const allIssues = state.sections.flatMap((s) =>
    s.issues.map((i) => ({ ...i, section: s.name }))
  )

  const mustFix = allIssues.filter((i) => i.severity === 'must-fix')
  const shouldFix = allIssues.filter((i) => i.severity === 'should-fix')
  const consider = allIssues.filter((i) => i.severity === 'consider')

  lines.push(`## Executive Summary`)
  lines.push(``)
  lines.push(`| Category | Count |`)
  lines.push(`|----------|-------|`)
  lines.push(`| Must Fix | ${mustFix.length} |`)
  lines.push(`| Should Fix | ${shouldFix.length} |`)
  lines.push(`| Consider | ${consider.length} |`)
  lines.push(`| **Total Issues** | **${allIssues.length}** |`)
  lines.push(``)

  lines.push(`## Section Scores`)
  lines.push(``)
  lines.push(`| Section | Score | Issues |`)
  lines.push(`|---------|-------|--------|`)

  for (const section of state.sections) {
    const score = calculateScore(section)
    lines.push(`| ${section.name} | ${score.toFixed(1)}/10 | ${section.issues.length} |`)
  }
  lines.push(``)

  const formatIssueList = (issues: typeof allIssues, severity: IssueSeverity) => {
    if (issues.length === 0) return

    const labels: Record<IssueSeverity, string> = {
      'must-fix': 'Must Fix',
      'should-fix': 'Should Fix',
      'consider': 'Consider',
    }

    lines.push(`## ${labels[severity]} Issues (${issues.length})`)
    lines.push(``)

    for (const issue of issues) {
      lines.push(`### ${issue.section}`)
      lines.push(``)
      lines.push(`- **Issue:** ${issue.description}`)
      if (issue.location) {
        lines.push(`- **Location:** "${issue.location}"`)
      }
      if (issue.suggestion) {
        lines.push(`- **Suggestion:** ${issue.suggestion}`)
      }
      lines.push(``)
    }
  }

  formatIssueList(mustFix, 'must-fix')
  formatIssueList(shouldFix, 'should-fix')
  formatIssueList(consider, 'consider')

  lines.push(`## Detailed Checklist Results`)
  lines.push(``)

  for (const section of state.sections) {
    const checked = section.checklist.filter((i) => i.checked).length
    const total = section.checklist.length
    lines.push(`### ${section.name} (${checked}/${total})`)
    lines.push(``)

    for (const item of section.checklist) {
      const status = item.checked ? '[x]' : '[ ]'
      const aiNote = item.aiSuggested !== undefined
        ? item.aiSuggested
          ? ' *(AI: Pass)*'
          : ' *(AI: Fail)*'
        : ''
      lines.push(`- ${status} ${item.label}${aiNote}`)
    }
    lines.push(``)
  }

  lines.push(`---`)
  lines.push(`*Generated by Paper Review App*`)

  return lines.join('\n')
}

export function ReportGenerator({ state, calculateScore }: ReportGeneratorProps) {
  const [copied, setCopied] = useState(false)
  const [showPreview, setShowPreview] = useState(false)

  const report = generateMarkdownReport(state, calculateScore)

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(report)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }, [report])

  const handleDownload = useCallback(() => {
    const blob = new Blob([report], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `paper-review-${state.paperTitle?.replace(/\s+/g, '-').toLowerCase() || 'report'}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }, [report, state.paperTitle])

  const handlePrint = useCallback(() => {
    const printWindow = window.open('', '_blank')
    if (!printWindow) return

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Paper Review Report</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
              padding: 40px;
              max-width: 800px;
              margin: 0 auto;
              line-height: 1.6;
            }
            h1 { border-bottom: 2px solid #333; padding-bottom: 10px; }
            h2 { margin-top: 30px; color: #333; }
            h3 { margin-top: 20px; color: #555; }
            table { border-collapse: collapse; width: 100%; margin: 20px 0; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background: #f5f5f5; }
            ul { list-style: none; padding-left: 0; }
            li { margin: 5px 0; }
            @media print {
              body { padding: 20px; }
            }
          </style>
        </head>
        <body>
          ${report
            .replace(/^# (.+)$/gm, '<h1>$1</h1>')
            .replace(/^## (.+)$/gm, '<h2>$1</h2>')
            .replace(/^### (.+)$/gm, '<h3>$1</h3>')
            .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
            .replace(/\*(.+?)\*/g, '<em>$1</em>')
            .replace(/^\| (.+) \|$/gm, (match) => {
              const cells = match.slice(1, -1).split('|').map(c => c.trim())
              return '<tr>' + cells.map(c => `<td>${c}</td>`).join('') + '</tr>'
            })
            .replace(/(<tr>.*<\/tr>\n?)+/g, '<table>$&</table>')
            .replace(/^- (.+)$/gm, '<li>$1</li>')
            .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
            .replace(/\n\n/g, '</p><p>')
            .replace(/^(?!<)(.+)$/gm, '<p>$1</p>')
          }
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }, [report])

  const totalIssues = state.sections.reduce((acc, s) => acc + s.issues.length, 0)

  return (
    <Card>
      <CardHeader>
        <CardTitle>Generate Report</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-3 gap-4 text-center">
          <div className="p-4 bg-gray-50 dark:bg-gray-800 rounded-lg">
            <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">
              {state.overallScore.toFixed(1)}
            </p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Overall Score</p>
          </div>
          <div className="p-4 bg-gray-50 dark:bg-gray-800 rounded-lg">
            <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">
              {state.sections.length}
            </p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Sections</p>
          </div>
          <div className="p-4 bg-gray-50 dark:bg-gray-800 rounded-lg">
            <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">
              {totalIssues}
            </p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Total Issues</p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <Button onClick={handleCopy} variant="secondary">
            {copied ? (
              <>
                <svg className="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg className="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
                </svg>
                Copy Markdown
              </>
            )}
          </Button>
          <Button onClick={handleDownload} variant="secondary">
            <svg className="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Download
          </Button>
          <Button onClick={handlePrint} variant="secondary">
            <svg className="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Print
          </Button>
          <Button onClick={() => setShowPreview(!showPreview)} variant="ghost">
            {showPreview ? 'Hide Preview' : 'Show Preview'}
          </Button>
        </div>

        {showPreview && (
          <div className="mt-4 p-4 bg-gray-50 dark:bg-gray-800 rounded-lg max-h-[500px] overflow-y-auto">
            <pre className="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap font-mono">
              {report}
            </pre>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
